version: '3'
services:
  mongodb:
     image: mongo
     container_name: mongo
     restart: always
     ports:
        - 27017:27017
     environment:
        - MONGO_INITDB_ROOT_USERNAME="secret"
        - MONGO_INITDB_ROOT_PASSWORD="adedayo2019"  
  redisdb:
      image: redis
      container_name: redis
      ports:
        - 6379:6379
  web:
    image: typescript_web
    build: ./
    depends_on:
       - mongodb
       - redisdb
    container_name: typescript_web
    restart: always
    environment: 
      - MONGODB_URI="mongodb+srv://test:test!!@cluster0-zrpla.mongodb.net/test?retryWrites=true&w=majority"
      - MONGODB_URI_LOCAL="mongodb://localhost:27017/test"
      - SESSION_SECRET="ashdfjhasdlkjfhalksdjhflak"
      - FACEBOOK_ID="754220301289665" 
      - FACEBOOK_SECRET="41860e58c256a3d7ad8267d3c1939a4a"
    ports:
      - 80:3000

# Test